import type { NextPage } from "next";
import Head from "next/head";

import { Children, Fragment, useState } from "react";
import axios from "axios";
import ReactLoading from "react-loading";
import "semantic-ui-css/semantic.min.css";
import { Button, Icon, Input, Table, Container } from "semantic-ui-react";
import Flag from "react-world-flags";

var all_universities = require("../assets/world_universities_and_domains");

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const [results, setResults] = useState<any[]>([]);

  const [isFirstSearch, setIsFirstSearch] = useState(false);
  const [loading, setLoading] = useState(false);

  const searchUniversities = () => {
    setLoading(true);

    setResults(
      all_universities.filter((university: any) =>
        university.name.toLowerCase().includes(input.toLowerCase())
      )
    );

    setIsFirstSearch(true);
    setLoading(false);
  };

  return (
    <div className="App">
      <Head>
        <title>Find University</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="App-main ">
        {loading === true && (
          <Fragment>
            <ReactLoading
              type="spin"
              color="#bd93f9"
              height={230}
              width={170}
            />
          </Fragment>
        )}
        {loading === false && (
          <Fragment>
            <br />
            <Input
              className="my-5"
              value={input}
              onKeyDown={(e: any) => e.keyCode === 13 && searchUniversities()}
              onChange={(e) => setInput(e.target.value)}
              icon="search"
              placeholder="Search University..."
            />
            <br /> <br />
            <Button
              size="huge"
              color="pink"
              onClick={() => searchUniversities()}
              animated
            >
              <Button.Content visible>Search</Button.Content>
              <Button.Content hidden>
                <Icon name="arrow right" />
              </Button.Content>
            </Button>
            <br />
            {isFirstSearch && (
              <Container>
                {results.length === 0 && (
                  <h1 className="mt-1 pt-5">
                    There is no university with this name.
                  </h1>
                )}
                {results.length !== 0 && (
                  <Table inverted>
                    <Table.Header>
                      <Table.Row>
                        <Table.HeaderCell>Country</Table.HeaderCell>
                        <Table.HeaderCell>University name</Table.HeaderCell>
                        <Table.HeaderCell>Web Page</Table.HeaderCell>
                      </Table.Row>
                    </Table.Header>
                    <Table.Body>
                      {results?.map((res, index) => (
                        <Table.Row key={index}>
                          <Table.Cell>
                            <Flag
                              style={{ marginLeft: "30px" }}
                              height="30"
                              code={res.alpha_two_code}
                            />
                          </Table.Cell>
                          <Table.Cell>
                            <p style={{ fontSize: "18px" }}>{res.name}</p>
                          </Table.Cell>
                          <Table.Cell>
                            <p style={{ fontSize: "18px" }}>
                              <a href={res.web_pages}>{res.web_pages}</a>
                            </p>
                          </Table.Cell>
                        </Table.Row>
                      ))}
                    </Table.Body>
                  </Table>
                )}
              </Container>
            )}
          </Fragment>
        )}
      </main>
    </div>
  );
};

export default Home;
