import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, useState } from "react";
import ReactLoading from "react-loading";
import "semantic-ui-css/semantic.min.css";
import { Container } from "semantic-ui-react";
import { MyTable } from "../components/MyTable";
import NotFoundText from "../components/mini-components/NotFoundText";
import MyInput from "../components/mini-components/MyInput";
import MyButton from "../components/mini-components/MyButton";
import Divider from "../components/mini-components/Divider";
import { Universities } from "../types/university.types";

const all_universities = require("../assets/world_universities_and_domains");

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const [results, setResults] = useState<Universities | null>(null);
  const [loading, setLoading] = useState(false);

  const searchUniversities = () => {
    setLoading(true);

    setResults(
      all_universities.filter((university: any) =>
        university.name.toLowerCase().includes(input.toLowerCase())
      )
    );

    setLoading(false);
  };

  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };

  return (
    <div className="App">
      <Head>
        <title>Find University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <main className="App-main">
        {loading && (
          <ReactLoading type="spin" color="#bd93f9" height={230} width={170} />
        )}

        {!loading && (
          <>
            <MyInput
              input={input}
              searchUniversities={searchUniversities}
              handleInput={handleInput}
            />
            <Divider />
            <MyButton searchUniversities={searchUniversities} />
            <Container>
              {results?.length === 0 && (
                <NotFoundText text="There is no university with this name." />
              )}
              {results && results?.length > 0 && <MyTable results={results} />}
            </Container>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
